# Import the libraries

In [1]:
#Import the torch library followed by torch.nn library as nn
import torch
import torch.nn as nn

# Assign inputs to the neuron

In [2]:
#Inputs to the neuron (Note: We have used random values here)
inputs = torch.tensor ([3.0,2.0,-1.0])

In [9]:
inputs

tensor([ 3.,  2., -1.])

In [10]:
#Create a neuron with 3 features and 1 output
neuron = nn.Linear(in_features=3,out_features=1)
output = neuron(inputs)

In [11]:
output

tensor([1.0027], grad_fn=<AddBackward0>)

# Print the output

In [12]:
#Print the final output of the neuron
print (output)

tensor([1.0027], grad_fn=<AddBackward0>)


# Weight of the neuron

In [13]:
#To view the weight of the neuron
neuron.weight

Parameter containing:
tensor([[-0.2463,  0.5084, -0.3197]], requires_grad=True)

# Bias of the neuron

In [14]:
#To view the bias of the neuron
neuron.bias

Parameter containing:
tensor([0.4052], requires_grad=True)

# Perceptron

In [17]:
model = nn.Sequential(nn.Linear(in_features=3,out_features=1),
    nn.ReLU(),
    nn.Linear(in_features=1,out_features=1),
    nn.Sigmoid())

In [65]:
inputs = torch.tensor ([2.0,4.0,6.0]).unsqueeze(1).T

In [66]:
inputs.shape

torch.Size([1, 3])

In [67]:
y_pred=model(inputs)

In [68]:
y_pred

tensor([[0.6865]], grad_fn=<SigmoidBackward0>)

In [69]:
list(model.named_parameters())

[('0.weight',
  Parameter containing:
  tensor([[ 0.5720, -0.2777, -0.4892]], requires_grad=True)),
 ('0.bias',
  Parameter containing:
  tensor([-0.1634], requires_grad=True)),
 ('2.weight',
  Parameter containing:
  tensor([[-0.8033]], requires_grad=True)),
 ('2.bias',
  Parameter containing:
  tensor([0.7838], requires_grad=True))]

In [70]:
model.eval()

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
  (1): ReLU()
  (2): Linear(in_features=1, out_features=1, bias=True)
  (3): Sigmoid()
)

In [71]:
import torch.optim as optim

In [72]:
criterion_bce = nn.BCELoss()
learning_rate = 0.001
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [94]:
y_actual=torch.tensor([1],dtype=torch.float32).unsqueeze(1)

In [95]:
y_actual

tensor([[1.]])

In [96]:
epochs = 1
for epoch in range(epochs):
    model.train()
    y_pred = model(inputs)
    loss = criterion_bce(y_pred, y_actual)
    loss.backward()
    optimizer.step()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

Epoch 1/1, Loss: 0.3755


In [97]:
y_pred_probs = model(X_test_tensor).unsqueeze(1)
y_pred = (y_pred_probs > 0.5)

In [98]:
y_pred_probs

tensor([[0.6298]], grad_fn=<UnsqueezeBackward0>)